n =(input('Digit algo: '))
print(type(n))
print('É um numéro?', n.isnumeric())
print('É alfabético?', n.isalpha())
print('É alfanumérico?', n.isalnum())
print('Só tem espaços?', n.isspace())
print('Está em maiúsculo?', n.isupper())
print('Está em minúsculo?', n.islower())
print('Está capitalizada?', n.istitle())
